---
- name: verify apache installation
  hosts: localhost

  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  
  - name: copy updated apache config file
    copy:
      src: /tmp/httpd.conf
      dest: /etc/httpd.conf
    notify:
    - Restart apache
  
  - name: Ensure apache is running
    service:
      name: httpd
      state: started
  
  handlers:
    - name: Restart apache
      service:
        name: httpd
        state: restarted