---
- name: Setup Apache Server
  hosts: localhost

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
    tags: i-httpd

  - name: start httpd
    service:
      name: httpd
      state: started
    tags: s-httpd