---
- name: Download package from yaml file
  hosts: localhost

  tasks:
  - name: Create a directory /opt/tomcat
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755
      owner: root
      group: root

  - name: Download tomcat using get_url
    get_url:
      url: https://centos.pkgs.org/7/centos-aarch64/screen-4.1.0-0.26.20120314git3c2946.el7.aarch64.rpm.html
      dest: /opt/tomcat
      mode: 0755